{
  aliases = {
    "cd" = "z";
    "grep" = "grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}";
    "egrep" = "grep -E";
    "fgrep" = "grep -F";
    "ls" = "eza";
    "l" = "eza -lah";
    "la" = "eza -lAh";
    "ll" = "eza -lh";
    "lsa" = "eza -lah";
    "md" = "mkdir -p";
    "rd" = "rmdir";
    "run-help" = "man";
    "which-command" = "whence";
  };
  abbrs = {
    "g" = "git";
    "ga" = "git add";
    "gaa" = "git add --all";
    "gam" = "git am";
    "gama" = "git am --abort";
    "gamc" = "git am --continue";
    "gams" = "git am --skip";
    "gamscp" = "git am --show-current-patch";
    "gap" = "git apply";
    "gapa" = "git add --patch";
    "gapt" = "git apply --3way";
    "gau" = "git add --update";
    "gav" = "git add --verbose";
    "gb" = "git branch";
    "gbD" = "git branch --delete --force";
    "gba" = "git branch --all";
    "gbd" = "git branch --delete";
    "gbg" = "LANG=C git branch -vv | grep \": gone\\]\"";
    "gbl" = "git blame -w";
    "gbm" = "git branch --move";
    "gbnm" = "git branch --no-merged";
    "gbr" = "git branch --remote";
    "gbs" = "git bisect";
    "gbsb" = "git bisect bad";
    "gbsg" = "git bisect good";
    "gbsn" = "git bisect new";
    "gbso" = "git bisect old";
    "gbsr" = "git bisect reset";
    "gbss" = "git bisect start";
    "gc" = "git commit --verbose";
    "gc!" = "git commit --verbose --amend";
    "gcB" = "git checkout -B";
    "gca" = "git commit --verbose --all";
    "gca!" = "git commit --verbose --all --amend";
    "gcam" = "git commit --all --message";
    "gcan!" = "git commit --verbose --all --no-edit --amend";
    "gcann!" = "git commit --verbose --all --date=now --no-edit --amend";
    "gcans!" = "git commit --verbose --all --signoff --no-edit --amend";
    "gcas" = "git commit --all --signoff";
    "gcasm" = "git commit --all --signoff --message";
    "gcb" = "git checkout -b";
    "gcf" = "git config --list";
    "gcl" = "git clone --recurse-submodules";
    "gclean" = "git clean --interactive -d";
    "gclf" = "git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules";
    "gcmsg" = "git commit --message";
    "gcn" = "git commit --verbose --no-edit";
    "gcn!" = "git commit --verbose --no-edit --amend";
    "gco" = "git checkout";
    "gcor" = "git checkout --recurse-submodules";
    "gcount" = "git shortlog --summary --numbered";
    "gcp" = "git cherry-pick";
    "gcpa" = "git cherry-pick --abort";
    "gcpc" = "git cherry-pick --continue";
    "gcs" = "git commit --gpg-sign";
    "gcsm" = "git commit --signoff --message";
    "gcss" = "git commit --gpg-sign --signoff";
    "gcssm" = "git commit --gpg-sign --signoff --message";
    "gd" = "git diff";
    "gdca" = "git diff --cached";
    "gdcw" = "git diff --cached --word-diff";
    "gds" = "git diff --staged";
    "gdt" = "git diff-tree --no-commit-id --name-only -r";
    "gdup" = "git diff @{upstream}";
    "gdw" = "git diff --word-diff";
    "gf" = "git fetch";
    "gfa" = "git fetch --all --tags --prune --jobs=10";
    "gfg" = "git ls-files | grep";
    "gfo" = "git fetch origin";
    "gg" = "git gui citool";
    "gga" = "git gui citool --amend";
    "ghh" = "git help";
    "gignore" = "git update-index --assume-unchanged";
    "gignored" = "git ls-files -v | grep \"^[[:lower:]]\"";
    "gl" = "git pull";
    "glg" = "git log --stat";
    "glgg" = "git log --graph";
    "glgga" = "git log --graph --decorate --all";
    "glgm" = "git log --graph --max-count=10";
    "glgp" = "git log --stat --patch";
    "glo" = "git log --oneline --decorate";
    "globurl" = "noglob urlglobber ";
    "glod" = "git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset\"";
    "glods" = "git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset\" --date=short";
    "glog" = "git log --oneline --decorate --graph";
    "gloga" = "git log --oneline --decorate --graph --all";
    "glol" = "git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\"";
    "glola" = "git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\" --all";
    "glols" = "git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\" --stat";
    "glp" = "_git_log_prettily";
    "gm" = "git merge";
    "gma" = "git merge --abort";
    "gmc" = "git merge --continue";
    "gmff" = "git merge --ff-only";
    "gms" = "git merge --squash";
    "gmtl" = "git mergetool --no-prompt";
    "gmtlvim" = "git mergetool --no-prompt --tool=vimdiff";
    "gp" = "git push";
    "gpd" = "git push --dry-run";
    "gpf" = "git push --force-with-lease --force-if-includes";
    "gpf!" = "git push --force";
    "gpoat" = "git push origin --all && git push origin --tags";
    "gpod" = "git push origin --delete";
    "gpr" = "git pull --rebase";
    "gpra" = "git pull --rebase --autostash";
    "gprav" = "git pull --rebase --autostash -v";
    "gpristine" = "git reset --hard && git clean --force -dfx";
    "gprv" = "git pull --rebase -v";
    "gpu" = "git push upstream";
    "gpv" = "git push --verbose";
    "gr" = "git remote";
    "gra" = "git remote add";
    "grb" = "git rebase";
    "grba" = "git rebase --abort";
    "grbc" = "git rebase --continue";
    "grbi" = "git rebase --interactive";
    "grbo" = "git rebase --onto";
    "grbs" = "git rebase --skip";
    "grev" = "git revert";
    "greva" = "git revert --abort";
    "grevc" = "git revert --continue";
    "grf" = "git reflog";
    "grh" = "git reset";
    "grhh" = "git reset --hard";
    "grhk" = "git reset --keep";
    "grhs" = "git reset --soft";
    "grm" = "git rm";
    "grmc" = "git rm --cached";
    "grmv" = "git remote rename";
    "grrm" = "git remote remove";
    "grs" = "git restore";
    "grset" = "git remote set-url";
    "grss" = "git restore --source";
    "grst" = "git restore --staged";
    "gru" = "git reset --";
    "grup" = "git remote update";
    "grv" = "git remote --verbose";
    "gsb" = "git status --short --branch";
    "gsd" = "git svn dcommit";
    "gsh" = "git show";
    "gsi" = "git submodule init";
    "gsps" = "git show --pretty=short --show-signature";
    "gsr" = "git svn rebase";
    "gss" = "git status --short";
    "gst" = "git status";
    "gsta" = "git stash push";
    "gstaa" = "git stash apply";
    "gstall" = "git stash --all";
    "gstc" = "git stash clear";
    "gstd" = "git stash drop";
    "gstl" = "git stash list";
    "gstp" = "git stash pop";
    "gsts" = "git stash show --patch";
    "gstu" = "git stash push --include-untracked";
    "gsu" = "git submodule update";
    "gsw" = "git switch";
    "gswc" = "git switch --create";
    "gta" = "git tag --annotate";
    "gts" = "git tag --sign";
    "gtv" = "git tag | sort -V";
    "gunignore" = "git update-index --no-assume-unchanged";
    "gunwip" = "git rev-list --max-count=1 --format=\"%s\" HEAD | grep -q \"\\\\--wip--\" && git reset HEAD~1";
    "gwch" = "git whatchanged -p --abbrev-commit --pretty=medium";
    "gwipe" = "git reset --hard && git clean --force -df";
    "gwt" = "git worktree";
    "gwta" = "git worktree add";
    "gwtls" = "git worktree list";
    "gwtmv" = "git worktree move";
    "gwtrm" = "git worktree remove";
  };
}
