{ inputs, ... }:
{
  imports = [
    inputs.treefmt-nix.flakeModule
    inputs.git-hooks.flakeModule
  ];

  perSystem =
    { config, pkgs, ... }:
    {
      treefmt = {
        projectRootFile = "flake.nix";
        programs.nixfmt.enable = true;
      };

      pre-commit.settings.hooks = {
        treefmt = {
          enable = true;
          package = config.treefmt.build.wrapper;
        };

        # The hardware configuration is generated by nixos-generate-config, so it is not ours to lint.
        statix = {
          enable = true;
          stages = [ "pre-push" ];
          settings.ignore = [ "configurations/nixos/hardware-configurations" ];
        };
        deadnix = {
          enable = true;
          stages = [ "pre-push" ];
          excludes = [ "configurations/nixos/hardware-configurations/.*" ];
        };
      };

      devShells.default = pkgs.mkShell {
        name = "dotfiles-shell";
        meta.description = "Dev environment for dotfiles";
        inputsFrom = [ config.pre-commit.devShell ];
        packages = [
          pkgs.nixd
          pkgs.nil
          pkgs.nh
          pkgs.just
          config.treefmt.build.wrapper
        ];
        # Point nh at this checkout only while inside its shell.
        shellHook = ''
          export NH_FLAKE="$PWD"
        '';
      };
    };
}
