name: Push Image (fastmri)

on:
  push:
    branches:
      - fastmri

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: slowGPU/burning_gpu
          path: burning_gpu
          token: ${{ secrets.GH_PAT }}
          sparse-checkout: |
            requirements.txt

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Projects/fastmri/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fastmri:latest
