name: Serve to Meadow

on:
  push:
    branches:
      - main

jobs:
  serve:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/meadow
            [ -d dotfiles ] || git clone https://github.com/${{ github.repository }}
            cd dotfiles
            git pull
            /usr/share/nginx/sbin/nginx -s reload
